### ISSUE TITLE
Email alters and External application launch are not working !!!

### ISSUE THREAD

**Issue by Suleman-Elahi** [R-Smith/tcpTrigger#4]
The software is able to show alert dialog, but its not launching the external application. Also, the email alerts are not working... :|

**Comment by r-smith** [comment]
Which external application are you launching?  Keep in mind that tcpTrigger runs as a service and you are not able to launch an interactive/GUI application.  Well you could, but the application would not show up in your desktop session.  The external application feature is meant launch things like scripts that do not need user interaction.  Check task manager to ensure the process is starting.

For the email issue - the application does not currently support TLS or authenticated connections.  Is that something your SMTP server requires?  If the email is failing to send, a failure reason should be recorded in your Windows event log.  tcpTrigger writes to the Application log with the Source name set to 'tcpTrigger'.

**Comment by tarmogr** [comment]
I made a generic .vbs script but it is not run by tcpTrigger

**Comment by r-smith** [comment]
Check the Windows event log - look under the Application log with the source of 'tcpTrigger'.  An entry is added if the external application fails to run, but no entry is added if the application/script executes.


Check taskmanager to see if wscript.exe or cscript.exe executes.  Maybe add a sleep statement to your script.


By default, the service runs as the built-in 'Local Service' account, which is very restricted.  Make sure the account can access your script.  You could try changing the logon account for the tcpTrigger service to 'System' for testing purposes.  In the configuration, maybe also turn off the rate limiting feature (under advanced in the gui) to help with testing.
