### ISSUE TITLE
Exclude IPs option

### ISSUE THREAD

**Issue by oneoffdallas** [R-Smith/tcpTrigger#5]
This is a handy little app and it works well! Is it still maintained? If so, an IP exclusion configuration option would be extremely helpful so admin machines or vulnerability scanners don't trigger an alert.

**Comment by r-smith** [comment]
Hi there! Yes, still maintained when I have time. IP exclusions is the #1 thing I want add. Right now I'm working on changing up the format of the configuration file and re-writing the GUI portion so that it doesn't use any 3rd party libraries. I'm hoping to have a new release out in 1 - 2 months.

**Comment by oneoffdallas** [comment]
Very cool! Looking forward to it and keep up the great work!

**Comment by r-smith** [comment]
Done! Check out the new release. A lot has changed.

Settings are lost on upgrade due to many of the changes. I felt it wasn't worth writing a settings upgrade routine.
