### ISSUE TITLE
On some systems, the .msi installer fails with error 1603

### ISSUE THREAD

**Issue by r-smith** [R-Smith/tcpTrigger#6]
On some systems, the .msi installer fails with error 1603. This issue was reported to me outside of GitHub. Please let me know if you are having this issue, as I am unable to recreate the problem.

Error in .msi debug log:
`ExecSecureObjects:  Error 0x80070534: failed to get sid for account: NT Authority\Local Service
CustomAction ExecSecureObjects_64 returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)`

It appears the installation is failing when attempting to register the tcpTrigger service in Windows. The installer sets the service to run as the built-in low privilege Local Service account and this seems to be the source of the failure.

If you encounter this error, collect a .msi installer log using:
`msiexec /i "c:\path\to\tcptrigger.setup.msi" /L*V "c:\log\tcptrigger.log"`

**Comment by jfeijoob** [comment]
Hi R-Smith

I have a log file,  but I prefer to not share it here because not sure about what sensible information can be there, I have checked, and it looks like there no sensible information. Let me know how to provide the file to you in a different way

Regards

**Comment by r-smith** [comment]
@jfeijoob - If you still have the installer log, can you email it to 4084199a-0a0f-4bd8-b73d-2d9e89d5418e@anonaddy.me

**Comment by roughnecks** [comment]
@R-Smith is that email still good? I have logs.

**Comment by r-smith** [comment]
@roughnecks can you try version 1.3.3 that was just released? I changed how the installer detects the .NET Framework install path. If you still get error 1603, can you send the logs? Yes, the email address is still valid.

**Comment by roughnecks** [comment]
> @roughnecks can you try version 1.3.3 that was just released? I changed how the installer detects the .NET Framework install path. If you still get error 1603, can you send the logs? Yes, the email address is still valid.

log sent.

**Comment by r-smith** [comment]
Looks like you're getting the same: `ExecSecureObjects:  Error 0x80070534: failed to get sid for account: NT Authority\Local Service`

If you don't mind, can you try manually registering the service?

## Manual install steps (partial)
1. Extract the 3 executable files from tcpTrigger.Setup.msi.
  a. Make a temp folder to extract the files to, like c:\temp.
  b. `msiexec /a "C:\PATH_TO_INSTALLER\tcpTrigger.Setup.msi" /qb targetdir="C:\TEMP"`
2. Create the folder `C:\Program Files\tcpTrigger`.
3. Move the 3 extracted executables from c:\temp\tcptrigger to c:\program files\tcptrigger.
4. Register the Windows service.
  a. Open an administrative command prompt.
  b. `sc.exe create tcpTrigger start= auto binPath= "C:\Program Files\tcpTrigger\tcpTrigger.exe" obj= "NT AUTHORITY\LocalService"`

Let me know if you're able to do these steps and what the sc.exe command returns. The sc.exe command is picky with the position of spaces, so copy/paste or enter exactly. The expected output is `[SC] CreateService SUCCESS`.

## Cleanup
1. Delete the Windows service (if the registration above was successful).
  a. From an administraive command prompt, run: `sc.exe delete tcptrigger`
  b. Expected output is `[SC] DeleteService SUCCESS`
2. Delete the folder `C:\Program Files\tcpTrigger`.
3. Delete the temp folder where you extracted the .msi contents.

**Comment by r-smith** [comment]
I've re-created the problem and pushed a fix. It was a localization issue. Try installing version 1.3.4.

The installer was referencing the built-in account *Local Service* using the English name. However, the *Local Service* account is named different depending on the language of the Windows installation, and this was causing the installer to fail. The installer now resolves and references the localized name for *Local Service*.

**Comment by roughnecks** [comment]
Sent you another log since it's still failing here..

**Comment by r-smith** [comment]
Can you try re-downloading and installing 1.3.4? I accidentally attached the 1.3.3 binary to the 1.3.4 release. It's fixed now.

**Comment by roughnecks** [comment]
> Can you try re-downloading and installing 1.3.4? I accidentally attached the 1.3.3 binary to the 1.3.4 release. It's fixed now.

yeah, working now, thanks.
sorry but wasn't there an option to show a popup as action? I remember it from when I installed tcpTrigger a while ago.. Now I only see logs and/or email (and email test is failing).

**Comment by r-smith** [comment]
The popup action was removed. In it's place, there's a new utility named **tcpTrigger Monitor**. Open that tool and select Options > Start tcpTrigger Monitor at logon.

If you're logged in, the tcpTrigger Monitor window pops up immediately when a connection is seen. I'm working on improving the documentation.

Is there an error for the email failure?

**Comment by roughnecks** [comment]
![image](https://user-images.githubusercontent.com/1666536/212756155-fa0714f8-819a-49f8-860c-ddbcdd605f5f.png)

I have set up an smtp server with auth. Used the same settings in cobian backup and they're working..
I'm also in contact with my mail server developer.

**Comment by r-smith** [comment]
Closing this issue. MSI error 1603 resolved in v1.3.4. Looking at the email error in a separate issue.
