### ISSUE TITLE
Help button in header doesn't work

### ISSUE THREAD

**Issue by MichaelEissner** [R-Smith/tcpTrigger#8]
The help button in headers doesn't work in the latest release (1.3.5)
![image](https://github.com/r-smith/tcpTrigger/assets/82372482/12bdc033-958b-443e-afc7-389a0fd19ec9)

**Comment by r-smith** [comment]
If you hover your mouse over the icon, the tooltip overlay displays. I've got it set to about a half second delay before the tooltip shows. If you click the icon instead of hovering, no tooltip shows.

I'm redesigning the GUI at the moment. I'll keep this in mind for the next release.
